### PR TITLE
#151 differentiate Congo COD and COG

### PR DESCRIPTION
**Pull request by bernard-ng**
There are in fact 2 Congo and this pull request aims to differentiate them in the display of results

### CODE REVIEW

**Review by MarienMupenda — COMMENTED** [review]
I think we should split congo into '**congo kinshasa**' and 'congo brazza'.

And add more cities in both.

**Review by MarienMupenda — APPROVED** [review]

**Review by ashkulz — CHANGES_REQUESTED** [review]
Please use `+` between words instead of spaces. Also, please add documentation or links on the origins of the names, as those of us outside the two regions cannot weigh in here.

**Comment by bernard-ng** [comment]
COG towns : https://fr.wikipedia.org/wiki/Liste_de_villes_de_la_r%C3%A9publique_du_Congo
COD towns : https://en.wikipedia.org/wiki/List_of_cities_in_the_Democratic_Republic_of_the_Congo

**Comment by ashkulz** [comment]
@bernard-ng I was talking more about the name of the region itself, "congo" vs "congo brazza".

**Comment by bernard-ng** [comment]
Owh agree, there is no particular documentation on the origin of the names, to differentiate the two Congo we often use the capital

Congo (kinshasa) => COD
Congo (brazzaville) or Congo (brazza) => COG

**Comment by MarienMupenda** [comment]
Or, with more details as you can find it below @ashkulz :

1. Democratic Republic of Congo => DR Congo (DRC) => Congo-Kinshasa => COD => CD
```json
"common": "DR Congo",
"official": "Democratic Republic of the Congo",
"capital": [
"Kinshasa"
],
"altSpellings": [
"CD",
"DR Congo",
"Congo-Kinshasa",
"Congo, the Democratic Republic of the",
"DRC"
],
"region": "Africa"
```
https://restcountries.com/v3.1/alpha/cod



2. Republic of the Congo (RC) => Congo-Brazzaville => COG => CG
```JSON
"common": "Republic of the Congo",
"official": "Republic of the Congo",
"capital": [
"Brazzaville"
],

"altSpellings": [
"CG",
"Congo",
"Congo-Brazzaville"
],
"region": "Africa"
```
https://restcountries.com/v3.1/alpha/cog

**Comment by ashkulz** [comment]
Hmm, I think https://en.wikipedia.org/wiki/Republic_of_the_Congo_(disambiguation) is also a decent explanation and reference. I think you should also change the existing `congo` definition and add the above link so that it's clear why it's being done. This will break a few links, but I think that's better than having a confusing name.

**Comment by MarienMupenda** [comment]
@bernard-ng I have made changes to the `congo` definition and added more cities, here is the pull request to your repository https://github.com/bernard-ng/most-active-github-users-counter/pull/1

**Comment by MarienMupenda** [comment]
> @bernard-ng I was talking more about the name of the region itself, "congo" vs "congo brazza".

To make it even more clear, this can be spelled `congo kinshasa` vs `congo brazzaville`

**Comment by ashkulz** [comment]
@bernard-ng can you rebase/squash the commits? Also, I think you didn't pickup [this commit](https://github.com/lauripiispanen/most-active-github-users-counter/pull/171/commits/d6304cc69f58413645ff5256060cba2e27c9f942) from @MarienMupenda.

**Comment by bernard-ng** [comment]
it's a bit confusing because there are two pull requests, mine and @MarienMupenda's, which is more up to date, I'll close this one so that the other one #171 is taken into account

**Pull request closed without merging**
